### ISSUE TITLE
Support for multiple games

### ISSUE THREAD

**Issue by Kandru** [RyroNZ/UE4MasterServer#1]
Hey,

thanks for your great project. To make the masterserver more reuseable I wish you could add support for multiple games. Every client and server should send a "unique" gameid to the host - and the host should just reply to the client only that hosts of that specific game.

Would be great if you could implement that.

**Comment by RyroNZ** [comment]
Well in theory it could already support multiple games, the client just needs to be written for each game. I kind of get what you're saying where one master server could host multiple games - but you could do that by running multiple servers on different ports easy enough (and use SRV records to point the domain to that specific port).

**Comment by Kandru** [comment]
Hey @RyroNZ,
that would be possible, yes. But I'm looking forward for a masterserver that can host different games without actually have the need to start more instances. I'm interested in providing unreal engine 4 users a free masterserver and don't want to invest much time to start / stop instances.

If it won't hurt you I maybe can create a pull request, but I didn't have much experience with python.

**Comment by RyroNZ** [comment]
OK - thanks for the suggestion will put that in when I get some time.

**Comment by Kandru** [comment]
Thanks for that. Pls reply to this issue if you made some progress. Would be great :)

**Comment by schobbent** [comment]
Hi @Kandru.

By "game" you means an application right ? Like "World of Warcraft", or "Metal gear" ?
Not a lobby (Some people use the term "Game" for lobby)

So in clear you would like to have a master server for all the different games you're developing (Ex : one where you're a ball, one which is an FPS, one where you're a spaceship) ?

Sorry, just trying to clarify all that.

**Comment by Kandru** [comment]
Hey @schobbent 

Yes, that's right. I mean unique games like World of Warcraft or Metal Gear. One masterserver for all the different games.

**Comment by RyroNZ** [comment]
Hey Kandru, I have added this in the client and server... I am currently at work so am unable to test it (I have literally just written the code and not tested it at all) so it may not even work... i'll fix it up at some stage.

If you wanted to grab it and test it that would be great! What i'll do later today is only send the serverlist for the specified GameID, as opposed to the whole lot and filtering it on the client.

**Comment by Kandru** [comment]
Hey @RyroNZ really thanks for that. I will see if I have the time at weekend tomorrow. If not then I can test it at least next weekend.
