### ISSUE TITLE
UE4.25.4 Not detecting the plugin

### ISSUE THREAD

**Issue by ThreeTimesFaster** [RyroNZ/UE4MasterServer#14]
Hi, first off I'd like to say that the idea of your plugin was perfect for a game I'm working on at the moment, so thank you for this plugin.
Sadly, Unreal Engine isn't detecting the plugin for me.

I followed your provided installation guide by pasting the "OnlineSubsystemPython" into a "Plugins" folder of the projects root directory.
I changed the .uproject configurations and then tried to run the project.
I had to make some changes to the plugin as some headers were not being detected (Object.h -> UObject/Object.h in the OnlineSubsystemPythonConfig.h)
I then ran a Build process in Visual Studio and opened my project but the plugin isn't being detected in the Plugin tab.
I tried to see if the "Create Advanced Session" node at least appeared in a GameInstance blueprint but it didn't either.
Do I need the AdvancedSessionPlugin installed as well, by any chance?

Apologies for the wall of text.

**Comment by RyroNZ** [comment]
Hey Ivan,

The AdvancedSessionPlugin is required for the Create Advanced Session but is not required to use the OnlineSubsystemPython plugin you can just use the standard CreateSession node if you wish.

If you’re unsure if the plugin is being created try deleting the binaries folder in the plugin and see if it gets re-made in the build process. If it does the plugin is activated.
You also need to specify the online subsystem in your engine config.

Cheers,
Ryan Post

**Comment by ThreeTimesFaster** [comment]
My apologies, turns out the problem was mainly with my Unreal Engine but I forgot to update here.
Not sure what happened to my Unreal Engine but it keeps giving me a "Failed to launch editor" error
I resorted to using the Unreal Engine source build from github and it works fine now.
Thanks much :D
