### ISSUE TITLE
Create session detected but failed

### ISSUE THREAD

**Issue by ThreeTimesFaster** [RyroNZ/UE4MasterServer#15]
Hi, apologies for the trouble once again.

I've managed to get the server up and running on my PC but when I attempt to Create a Session in my game, it fails.
My command prompt shows as follows:
The part highlighted in yellow is me attempting to create a lobby session twice but both times failed.
![image](https://user-images.githubusercontent.com/35888980/99861303-a4064b80-2bd0-11eb-9d30-38689d4586fc.png)

This is how I set up my blueprints to create the lobby:
![image](https://user-images.githubusercontent.com/35888980/99861661-be8cf480-2bd1-11eb-9b1d-cc8144d02f7d.png)

The Create Session node results in failure and I also get the error message connected to the On Failure execution
Also, I attempted to Create a Session on a different PC but it gets stuck while attempting to do so.
The command prompt doesn't pick up this other PCs attempt to create a session.
So I think I might have set up my configurations wrongly.

This is my configurations for the Python file:
![image](https://user-images.githubusercontent.com/35888980/99861846-9f429700-2bd2-11eb-82ff-f9057943e160.png)

And this is my configurations for the source file in the plugin:
![image](https://user-images.githubusercontent.com/35888980/99861904-ce590880-2bd2-11eb-8eda-b88e68d50ad2.png)

Apologies for the information dump as well
I hope I can get your insight on what might be the problem.
Thanks regardless.

**Comment by ThreeTimesFaster** [comment]
Ok, I figured out a problem to the first part where I couldn't create a session on the PC that is running the server as well.
In the python file, line 76, "if (cherrypy.request.remote.ip != "127.0.0.1"):", the IP address should also be changed to fit the one being used

**Comment by ThreeTimesFaster** [comment]
Now my next problem is that I can't seem to Create Session/Join Session from another PC on another network
I think I've narrowed down the issue to it being either a port forwarding issue or IP address connection issue.
Running ping commands in cmd returned "request timed out" errors so that might the problem.
As for the solution, I attempted to opens ports as well as mess around with my firewall (even turning it off for both PCs) but they can't seem to ping each other

**Comment by ThreeTimesFaster** [comment]
I just tried running the other PC on the same network this time and surprisingly, it also doesn't work.
It was able to detect a session being created by the server PC but it can't join it and it also can't create its own session.

**Comment by ThreeTimesFaster** [comment]
I just realized that when I run the server and create a lobby, it is unable to get any information of the session aside from the number of players (refer to the 1st picture in this post)

**Comment by RyroNZ** [comment]
Hey Ivan, 

This is not designed to be used in a shipped product just for testing purposes (at least until additional things are added, but I don't have the time to be working on this). 

It doesn't directly include LAN support (what may need to happen is pass both the local ip and remote ip and then test local first and then remote but its unsupported atm).

As far as session information you need to set this manually and unless you add extra code we only have support for the specific key pairs

SERVERNAME
MAPNAME
GAMEMODE
PASSWORDPROTECTED
PLAYERCOUNT

Cheers,
Ryan Post

**Comment by ThreeTimesFaster** [comment]
That explains quite a fair bit.
Sorry for the trouble and thanks for replying.
