### ISSUE TITLE
Cannont load the plugin

### ISSUE THREAD

**Issue by muckermaus** [RyroNZ/UE4MasterServer#2]
![ue4-master](https://cloud.githubusercontent.com/assets/6241958/10313931/606e4848-6c52-11e5-8577-cace909fb5ae.PNG)

**Comment by RyroNZ** [comment]
Hi muckermaus, what version of UE4 are you using? I have tested it on 4.7, 4.8 and 4.9(.2) and not had any issues. What is the folder structure that you have the plugin in? and is it setup as a Engine or Project plugin?
Thanks,
Ryan

**Comment by muckermaus** [comment]
I have testing that in 4.9 as Project plugin.

**Comment by Dids** [comment]
Doesn't seem to be working on 4.10 either. :(

```
Project could not be compiled. Try rebuilding from source manually.
```

**Comment by Dids** [comment]
Seems to be compiling fine now on 4.10.
